### ISSUE TITLE
Domain doesn't work

### ISSUE THREAD

**Issue by Pegoku** [kubectyl/kuber#1]
![image](https://user-images.githubusercontent.com/81113533/202529345-21f72684-f5b9-4b26-9442-51e40fda180b.png)

**Comment by andrei0465** [comment]
The website is temporarily closed because the project has not yet reached a usable version. Soon it will be open with documentation + discourse platform for discussions (https://discourse.kubectyl.org)
When it will be available I will announce it on discord, so stay tuned.
